version: '3.9'
services:
  metabase-clickhouse:
    build: metabase-dockerfile/.
    container_name: metabase-clickhouse
    hostname: metabase
    volumes: 
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-app-db"
      - "MB_EMAIL_SMTP_HOST=maildev-sub"
      - "MB_EMAIL_SMTP_PASSWORD=password"
      - "MB_EMAIL_SMTP_PORT=25"
      - "MB_EMAIL_SMTP_SECURITY=none"
      - "MB_EMAIL_SMTP_USERNAME=admin"
      - "MB_ENABLE_XRAYS=false"
      - "MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=FALSE"
    cpus: 1
    mem_limit: 1024mb
    networks: 
      - metanet1-clickhouse
    depends_on: 
      postgres-app-db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres-app-db:
    image: postgres:15.2-alpine
    container_name: postgres-app-db
    hostname: postgres-app-db
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1-clickhouse
    cpus: 1
    mem_limit: 128m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  setup-clickhouse:
    image: bash:5.1.16
    container_name: setup-clickhouse
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1-clickhouse
    depends_on:
      metabase-clickhouse:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m
  clickhouse:
    image: clickhouse/clickhouse-server:22-alpine
    container_name: clickhouse
    hostname: clickhouse
    environment:
      - CLICKHOUSE_DB=ecommerce
      - CLICKHOUSE_USER=username
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=password
    networks: 
      - metanet1-clickhouse
    volumes:
      - $PWD/data-origin/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/?user=username&password=password&query=SELECT%201 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  maildev-sub-clickhouse:
    image: maildev/maildev:1.1.0
    container_name: maildev-sub-clickhouse
    hostname: maildev-sub
    ports:
    - "3001:80"
    networks:
    - metanet1-clickhouse
    cpus: 1
    mem_limit: 128m
networks: 
  metanet1-clickhouse:
    driver: bridge